"""auto

Revision ID: 5518ca403ace
Revises: 7d4ce2fe50f9
Create Date: 2026-03-08 19:49:40.940136

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5518ca403ace'
down_revision = '7d4ce2fe50f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('CachedLocations')
    op.drop_table('CachedToonInfo')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('CachedToonInfo',
    sa.Column('character_id', sa.BIGINT(), nullable=False),
    sa.Column('character_name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('corporation_id', sa.BIGINT(), nullable=False),
    sa.Column('corporation_name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('alliance_id', sa.BIGINT(), nullable=True),
    sa.Column('alliance_name', sa.VARCHAR(length=255), nullable=True),
    sa.Column('wallet_balance', sa.FLOAT(), nullable=True),
    sa.PrimaryKeyConstraint('character_id')
    )
    op.create_table('CachedLocations',
    sa.Column('location_id', sa.BIGINT(), nullable=False),
    sa.Column('location_name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('location_cost_index', sa.FLOAT(), nullable=True),
    sa.Column('location_cost_index_last_updated', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('location_id')
    )
    # ### end Alembic commands ###
