"""auto

Revision ID: 6e6bb2139b63
Revises: 16de3629350e
Create Date: 2026-03-10 00:05:04.867935

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e6bb2139b63'
down_revision = '16de3629350e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('CachedToonInfo')
    op.drop_table('CachedLocations')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('CachedLocations',
    sa.Column('location_id', sa.BIGINT(), nullable=False),
    sa.Column('location_name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('location_cost_index', sa.FLOAT(), nullable=True),
    sa.Column('location_cost_index_last_updated', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('location_id')
    )
    op.create_table('CachedToonInfo',
    sa.Column('character_id', sa.BIGINT(), nullable=False),
    sa.Column('character_name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('corporation_id', sa.BIGINT(), nullable=False),
    sa.Column('corporation_name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('alliance_id', sa.BIGINT(), nullable=True),
    sa.Column('alliance_name', sa.VARCHAR(length=255), nullable=True),
    sa.Column('wallet_balance', sa.FLOAT(), nullable=True),
    sa.PrimaryKeyConstraint('character_id')
    )
    # ### end Alembic commands ###
