"""auto

Revision ID: b427b3697797
Revises: 6e6bb2139b63
Create Date: 2026-03-10 10:43:49.543309

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b427b3697797'
down_revision = '6e6bb2139b63'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('CachedToonInfo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cached_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('CachedToonInfo', schema=None) as batch_op:
        batch_op.drop_column('cached_at')

    # ### end Alembic commands ###
